import type { NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import SportsSoccerIcon from "@mui/icons-material/SportsSoccer";

import * as Styled from "./index.styled";
import { Tab, Tabs } from "@mui/material";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Scoreme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Styled.Header>
        <Image src="/images/logo.png" alt="logo" width="100" height="100" />
      </Styled.Header>
      <Styled.Navbar>
        <Styled.NavTabs
        //value={value}
        //onChange={handleChange}
        >
          <Tab value="one" label="Item One" />
          <Tab value="two" label="Item Two" />
          <Tab value="three" label="Item Three" />
        </Styled.NavTabs>
      </Styled.Navbar>
    </>
  );
};

export default Home;
