import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import { Button as MuiButton } from "@mui/material";

const Button = styled(MuiButton)`
  background-color: #0066ff;
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button>Click me</Button>
      <Button>Test</Button>
    </>
  );
};

export default Home;
